version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${RDB_URL}
      - SPRING_DATASOURCE_USERNAME=${RDB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${RDB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - FASTAPI_HOST=${FASTAPI_HOST}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - goodjob-net

networks:
  goodjob-net:
    driver: bridge
