name: Deploy goodJob_Client to S3

on:
  push:
    branches:
      - dev_front

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Hunian
        env:
          HUNIAN_USER: ${{ secrets.HUNIAN_USER }}
          HUNIAN_HOST: ${{ secrets.HUNIAN_HOST }}
          HUNIAN_PASSWORD: ${{ secrets.HUNIAN_PASSWORD }}
        run: |
          sshpass -p "$HUNIAN_PASSWORD" ssh -o StrictHostKeyChecking=no $HUNIAN_USER@$HUNIAN_HOST << 'EOF'
            cd /home/hun/Desktop/goodjob/CV_Search

            git pull origin dev_front

            echo "ðŸ—ï¸ Building project..."
            npm run build

            echo "ðŸ§¹ Cleaning old process..."
            pm2 delete goodjob || true

            echo "ðŸš€ Starting static server on port 3013..."
            pm2 start "npx serve -s dist -l 3013" --name goodjob
          EOF